spring:
  application:
      name: cachemanageapp
  datasource: 
        driverClassName: com.mysql.jdbc.Driver
        url: "jdbc:mysql://localhost:3308/BOOKMANAGER?autoreconnect=true"
        password: "amaresh"
        username: "root"
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 1
        max-active: 15
        max-idle: 10
        max-wait: 8000